formatVersion: 1
inputs: {}
resources:
  Cloud_vSphere_Network_1:
    type: Cloud.vSphere.Network
    properties:
      networkType: existing
  Cloud_vSphere_Machine_1:
    type: Cloud.vSphere.Machine
    properties:
      image: jwhite-CentOS7
      cpuCount: 1
      totalMemoryMB: 2048
      networks:
        - network: '${resource.Cloud_vSphere_Network_1.id}'
      cloudConfig: |
        #cloudconfig
        fqdn: ${self.resourceName}.thewhiteshouse.net
        hostname: ${self.resourceName}
        repo_update: true
        repo_upgrade: all
        package_update: true
        package_upgrade: all
        runcmd:
         - echo root:VMware1\!|sudo chpasswd
         - sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
         - sed -i 's/\#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
         - sed -i 's/\#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
         - service sshd restart
         - yum -y groupinstall 'KDE' 'X Window System'
         - systemctl set-default graphical.target
         - init 5
